version: "3"
services:
    web:
        build: .
        ports: 
            - "3000:3000"
        depends_on:
            - database
    database:
        image: "mysql"
        restart: always
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - 3306:3306
        expose: 
            - 3306 
        volumes: 
            - my-db:/mysql
volumes: 
    my-db:

